name: 'Deploy Node.js Backend to EC2'
description: 'Deploys a Node.js backend app to EC2 via SCP and SSH'

inputs:
  host:
    description: EC2 public IP / DNS
    required: true
  username:
    description: SSH user
    required: true
  key:
    description: Private SSH key (use a GitHub secret in the workflow)
    required: true
  app-name:
    description: Name to give the PM2 process
    required: true
  target:
    description: Remote path where the code will live
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload backend to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        source: "."
        target: ${{ inputs.target }}
        strip_components: 1

    - name: Run backend on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        script: |
          cd ${{ inputs.target }}
          npm install
          /usr/bin/pm2 restart ${{ inputs.app-name }} || /usr/bin/pm2 start server.js --name ${{ inputs.app-name }}
